In [2]:
# importing libraries

import pandas as pd
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
import os
from pathlib import Path

In [19]:
# Importing Dataframe and sense checking

h10k = pd.read_csv('hansard10000.csv')

print(h10k.shape)
h10k.head(3)

(10000, 8)

,speech,party,constituency,date,speech_class,major_heading,year,speakername
0,We will now suspend for three minutes for sani...,Conservative,Ribble Valley,2021-03-11,Speech,Contingencies Fund (No. 2) Bill,2021,Nigel Evans
1,I am now beginning to share the indignation of...,Labour,City of Chester,2020-11-24,Speech,Exiting the European Union,2020,Christian Matheson
2,"The hon. Lady is wrong; as a matter of fact, w...",Conservative,Newark,2021-02-10,Speech,Building Safety,2021,Robert Jenrick

In [20]:
# Listing out the different parties, the different entries in 'speech_class'
# counting the nr. of speeches less thatn 1000 characters

print(h10k['party'].value_counts(), '\n')
print(h10k['speech_class'].value_counts(), '\n')
print("Nr. of speeches under 1000 ch.:", (h10k['speech'].str.len() < 1000).sum())

party
Conservative                        6192
Labour                              1828
Scottish National Party              560
Labour (Co-op)                       280
Liberal Democrat                     221
Speaker                              208
Democratic Unionist Party            140
Independent                           58
Plaid Cymru                           51
Social Democratic & Labour Party      21
Green Party                           17
Alliance                              12
Alba Party                             1
Name: count, dtype: int64

speech_class
Speech        9614
Procedural     343
Division        43
Name: count, dtype: int64

Nr. of speeches under 1000 ch.: 7752

In [23]:
# Replacing 'Labour Co-op' with 'Labour', dropping all parties except top 4, sense checking

h10k['party'] = hrd10k['party'].replace('Labour (Co-op)', 'Labour')
h10k = h10k[h10k['party'].isin(['Conservative', 'Labour', 'Scottish National Party', 'Liberal Democrat'])]
h10k['party'].value_counts()

party
Conservative               6192
Labour                     2108
Scottish National Party     560
Liberal Democrat            221
Name: count, dtype: int64

In [30]:
# Removing ll non 'speech' entries from 'speech class'
# Removing all speeches under 1000 characters and sense checking

h10k = h10k[h10k['speech_class'].isin(['Speech'])]

h10k = h10k[h10k['speech'].str.len() > 1000]

print('Shape of the dataframe:', h10k.shape)

h10k.head()

Shape of the dataframe: (2111, 8)

,speech,party,constituency,date,speech_class,major_heading,year,speakername
2,"The hon. Lady is wrong; as a matter of fact, w...",Conservative,Newark,2021-02-10,Speech,Building Safety,2021,Robert Jenrick
5,"Given that this was outlined earlier today, it...",Conservative,Great Yarmouth,2021-04-13,Speech,Northern Ireland,2021,Brandon Lewis
7,The aftermath of the 2008 crisis saw not only ...,Labour,"Sheffield, Hallam",2021-02-23,Speech,Government's Management of the Economy,2021,Olivia Blake
17,The right hon. Gentleman puts it correctly. Wh...,Conservative,Sutton and Cheam,2020-12-07,Speech,United Kingdom Internal Market Bill,2020,Paul Scully
18,"As always, I am grateful to the hon. Gentleman...",Conservative,North East Somerset,2021-01-28,Speech,Business of the House,2021,Jacob Rees-Mogg